import 'package:flutter/widgets.dart';

import 'app.dart';

void main() {
  //Créer une liste de product (objet List)
  /*final listProduct = [
    Product(
      name: "Smartphone X",
      description: "Latest flagship phone",
      price: 999.99,
      image: "assets/phone.png",
      category: "Electronics",
    ),
    Product(
      name: "Laptop Pro",
      description: "Powerful workstation",
      price: 1499.00,
      image: "assets/laptop.png",
      category: "Electronics",
    ),
    Product(
      name: "Wireless Buds",
      description: "Noise cancelling audio",
      price: 199.50,
      image: "assets/buds.png",
      category: "Audio",
    ),
    Product(
      name: "Smart Watch",
      description: "Fitness and notifications",
      price: 299.00,
      image: "assets/watch.png",
      category: "Wearables",
    ),
    Product(
      name: "Gaming Console",
      description: "4K gaming system",
      price: 499.99,
      image: "assets/console.png",
      category: "Gaming",
    ),
    Product(
      name: "Bluetooth Speaker",
      description: "Waterproof portable sound",
      price: 89.00,
      image: "assets/speaker.png",
      category: "Audio",
    ),
    Product(
      name: "Coffee Maker",
      description: "Automatic espresso machine",
      price: 120.00,
      image: "assets/coffee.png",
      category: "Home",
    ),
    Product(
      name: "Air Fryer",
      description: "Healthy cooking appliance",
      price: 150.00,
      image: "assets/fryer.png",
      category: "Home",
    ),
    Product(
      name: "Mechanical Keyboard",
      description: "RGB backlit keys",
      price: 130.00,
      image: "assets/keyboard.png",
      category: "Electronics",
    ),
    Product(
      name: "Gaming Mouse",
      description: "High DPI precision",
      price: 75.00,
      image: "assets/mouse.png",
      category: "Electronics",
    ),
    Product(
      name: "4K Monitor",
      description: "32-inch ultra HD display",
      price: 350.00,
      image: "assets/monitor.png",
      category: "Electronics",
    ),
    Product(
      name: "Office Chair",
      description: "Ergonomic leather chair",
      price: 210.00,
      image: "assets/chair.png",
      category: "Furniture",
    ),
    Product(
      name: "Desk Lamp",
      description: "LED with wireless charging",
      price: 45.00,
      image: "assets/lamp.png",
      category: "Home",
    ),
    Product(
      name: "Running Shoes",
      description: "Lightweight athletic gear",
      price: 110.00,
      image: "assets/shoes.png",
      category: "Fashion",
    ),
    Product(
      name: "Leather Wallet",
      description: "Genuine cowhide wallet",
      price: 35.00,
      image: "assets/wallet.png",
      category: "Fashion",
    ),
    Product(
      name: "Backpack",
      description: "Water-resistant travel bag",
      price: 65.00,
      image: "assets/backpack.png",
      category: "Fashion",
    ),
    Product(
      name: "Yoga Mat",
      description: "Non-slip eco-friendly mat",
      price: 30.00,
      image: "assets/yoga.png",
      category: "Sports",
    ),
    Product(
      name: "Dumbbell Set",
      description: "Adjustable weight plates",
      price: 80.00,
      image: "assets/weights.png",
      category: "Sports",
    ),
    Product(
      name: "Electric Toothbrush",
      description: "Sonic cleaning technology",
      price: 95.00,
      image: "assets/toothbrush.png",
      category: "Health",
    ),
    Product(
      name: "Hair Dryer",
      description: "Professional salon quality",
      price: 55.00,
      image: "assets/dryer.png",
      category: "Health",
    ),
    Product(
      name: "Microwave Oven",
      description: "Stainless steel 1000W",
      price: 180.00,
      image: "assets/microwave.png",
      category: "Home",
    ),
    Product(
      name: "Tablet Air",
      description: "Thin and light computing",
      price: 599.00,
      image: "assets/tablet.png",
      category: "Electronics",
    ),
    Product(
      name: "External SSD",
      description: "1TB fast storage",
      price: 125.00,
      image: "assets/ssd.png",
      category: "Electronics",
    ),
    Product(
      name: "Action Camera",
      description: "4K waterproof recording",
      price: 250.00,
      image: "assets/camera.png",
      category: "Electronics",
    ),
    Product(
      name: "Winter Jacket",
      description: "Insulated heavy coat",
      price: 160.00,
      image: "assets/jacket.png",
      category: "Fashion",
    ),
    Product(
      name: "Sunglasses",
      description: "Polarized UV protection",
      price: 140.00,
      image: "assets/glasses.png",
      category: "Fashion",
    ),
    Product(
      name: "Electric Kettle",
      description: "Fast boiling glass kettle",
      price: 40.00,
      image: "assets/kettle.png",
      category: "Home",
    ),
    Product(
      name: "Robot Vacuum",
      description: "Smart mapping technology",
      price: 320.00,
      image: "assets/vacuum.png",
      category: "Home",
    ),
    Product(
      name: "Drone Quadcopter",
      description: "GPS and 1080p camera",
      price: 450.00,
      image: "assets/drone.png",
      category: "Gaming",
    ),
    Product(
      name: "Electric Guitar",
      description: "Solid body classic design",
      price: 550.00,
      image: "assets/guitar.png",
      category: "Music",
    ),
  ];*/
  //Afficher le prix du premier (méthode print)
  //print(listProduct.first.getPriceInEuro());
  runApp(FlutterShopApp());
}
